footer:
  links:
    - title: Codes sources
      url: https://git.opendatafrance.net/validata
header:
  links:
    - title: Mode d'emploi
      url: https://opendatafrance.gitbook.io/validata/
    - title: API Validata
      url: https://api.validata.etalab.studio/apidocs
    - title: schema.data.gouv.fr
      url: https://schema.data.gouv.fr
    - title: Guide Schémas
      url: https://guides.etalab.gouv.fr/producteurs-schemas/#a-qui-s-adresse-ce-guide
    - title: Espace de discussion schémas
      url: https://github.com/etalab/schema.data.gouv.fr/issues
homepage:
  sections:
    - name: schema-datagouvfr
      title: Présentation
      description: "Validata est une plateforme de validation de données ouvertes. Elle offre à ses utilisateurs la possibilité de vérifier la conformité de leurs données par rapport aux schémas de données nationaux de référence, répertoriés sur schema.data.gouv.fr. <br /><br />Depuis Mars 2022 l’association OpenDataFrance et Etalab mettent à disposition une version unique et commune de cette plateforme dans le cadre d’une coopération renforcée en matière de gouvernance et de stratégie sur les sujets liés à la standardisation des données ouvertes à l’échelle nationale. <br /><br />Cette plateforme commune résulte des travaux d’unification de leurs démarches et de leurs ressources respectives en matière de standardisation. <br/><br /><h2>schema.data.gouv.fr</h2>Sélectionner un schéma référencé sur schema.data.gouv.fr :"
      catalog: https://schema.data.gouv.fr/schemas/schemas.json
    - name: schema-scdl
      title: Socle Commun des données locales
      description: Schémas à destination des collectivités territoriales dont la publication des données est considérée comme prioritaire.
      catalog: https://schema.data.gouv.fr/schemas/schemas-scdl.json
    # If `name: schema-transport` is changed, get in touch with the transport.data.gouv.fr team
    - name: schema-transport
      title: transport.data.gouv.fr
      description: Schémas mis en avant par transport.data.gouv.fr, relatifs à la mobilité et aux transports.
      catalog: https://schema.data.gouv.fr/schemas/schemas-transport-data-gouv-fr.json
